spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        group: amp-intel

    gateway:
      server:
        webflux:
          routes:
            - id: system-service
              uri: lb://system-service
              predicates:
                - Path=/api/system/**
              filters:
                - StripPrefix=2
